services:
  mc:
    image: itzg/minecraft-server
    container_name: "Minecraft"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      #RCON_PASSWORD: YourPassword
      MEMORY: "8G"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: '$$2a$$10$$hNtXHlcwJ0/pBA.IdEtso.7k8RQMw51Bk7ehw3TEGMVADK/U8WQuG' #Replace by your own key
      CF_MODPACK_MANIFEST: /modpack/manifest.json
      CF_SLUG: "custom"
      VANILLATWEAKS_SHARECODE: 2MGUix #Replace by your own VanillaTweaks code
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./modpack:/modpack

# https://docker-minecraft-server.readthedocs.io/en/latest/